# Generated by Django 2.2.2 on 2019-07-08 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of Worker', max_length=50)),
                ('company', models.CharField(help_text='Name of Company', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'worker',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of Order', max_length=100)),
                ('description', models.TextField(help_text='Description')),
                ('deadline', models.DateField(help_text='Deadline of the order')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='WorkerOrderAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.WorkOrder')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Worker')),
            ],
            options={
                'db_table': 'worker_order_assignment',
            },
        ),
    ]
